packages:
  - 'benchmark'
  - 'packages/*'
allowBuilds:
  esbuild: false
  microtime: false
  nx: false
  sharp: false
  unrs-resolver: false
overrides:
  zod: 4.3.6
linkWorkspacePackages: true
minimumReleaseAge: 4320
